theme: minima
title: Samim Dawood | Software Engineering ePortfolio
description: A showcase of full-stack development, system optimization, and secure software design. This Capstone portfolio highlights my ability to bridge the gap between complex algorithms and user-centric applications.
